server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: diankuaigong.ntg520.cn:18001
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露端口

