server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从服务在注册中心动态创建路由的功能
      routes: # 可以配置多个路由
        - id: payment_routh # 路由id，没有固定规则但要求唯一
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/getPayment/** # 路径相匹配的进行路由
            - After=2020-08-26T17:07:03.043+08:00[Asia/Shanghai] #在这个时间后菜生效
#            - Cookie=username,wxh #访问者必须带cookie，curl http://localhost:9527/payment/getPayment/1 --cookie "username=wxh"
#            - Header=X-Request-Id, \d+

        - id: payment_routh2 # 路由id，没有
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/create # 路径相匹配的进行路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka:  true
      fetch-registry:  true
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群:7001/eureka
